### ISSUE TITLE
Should tranisition function get the output of combiner ?

### ISSUE THREAD

**Issue by ksachdeva** [yjlolo/pytorch-deep-markov-model#4]
Hi @yjlolo 

I started to read this paper and came across your implementation. It is quite neatly written.

As I was going through the code I noticed the following 

https://github.com/yjlolo/pytorch-deep-markov-model/blob/3e606a3a4e2cf3474038b8fa539c6d8525d44abe/model/model.py#L112

Extracting the relevant parts here. Note the comment with prefix "KS"

```
for t in range(T_max):
            # q(z_t | z_{t-1}, x_{t:T})
            mu_q, logvar_q = self.combiner(h_rnn[:, t, :], z_prev,
                                           rnn_bidirection=self.rnn_bidirection)
            zt_q = self.reparameterization(mu_q, logvar_q)
            z_prev = zt_q
            # p(z_t | z_{t-1})
            # KS : You are supplying z_prev that is the output of combiner module
            #.        to the transition function
            mu_p, logvar_p = self.transition(z_prev)
            zt_p = self.reparameterization(mu_p, logvar_p)
```

The paper is not very clear about it but the way I have interpreted it so far is as follows -

The transition function (model) is a sort of a "learned prior". This is unlike regular VAE where a prior is assumed to be standard normal. So we use `p` for it.

The combiner function (model) is the approximate i.e. `q` and one would do KL on these `p` and `q`. You do that as well.

The part that is not clear in your above code is why `self.transition` should receive the input which is the output of `combiner` function. Shouldn't transition also get the original `z_prev`

If you look at another implementation of this model (in pytorch) https://github.com/guxd/deepHMM/blob/b1f596ee41f81c77ae20244c69092da184b5bcc9/models/dhmm.py#L83, the author uses the original z_prev

Honestly, the paper is not clear about it so not sure what is the right solution here.

Would appreciate your guidance and insight here

Regards
Kapil

**Comment by yjlolo** [comment]
Hi! 

> The part that is not clear in your above code is why self.transition should receive the input which is the output of combiner function. Shouldn't transition also get the original z_prev

I guess when you refer to the equation (6) in the paper, when `t>1`, corresponding to the third term, the expectation is taken over `z_{t-1}` sampled from `q` which is the output from the combiner. So the transition probability `p(z_t | z_{t-1})` is a function of the output from the combiner. 

>If you look at another implementation of this model (in pytorch) https://github.com/guxd/deepHMM/blob/b1f596ee41f81c77ae20244c69092da184b5bcc9/models/dhmm.py#L83, the author uses the original z_prev

I think the main discrepancy here is it seems they don't distinguish when `t=1` and `t>1`, referred to the second and the third term in eq (6) respectively. I follow the paper in a sense that `p(z_1)` is fixed (see [this line](https://github.com/yjlolo/pytorch-deep-markov-model/blob/3e606a3a4e2cf3474038b8fa539c6d8525d44abe/model/model.py#L125), which actually follows [this](https://github.com/clinicalml/dmm/blob/3a2e8cec5e58c5a141a6da6e685378e269e69bb8/model_th/dmm.py#L184) in the original repo provided by the author), and that `p(z_t | z_{t-1})` is inferred from `z_{t-1}` output by the combiner (as described above). 

Though different, I would doubt if it results in any significant difference in practice, which needs to be verified through experiments. 

Also note that I have not been able to reproduce the numbers reported in the paper and I am happy to receive more feedback.
Let me know if you have further doubts.

**Comment by ksachdeva** [comment]
Thanks, @yjlolo for taking the time to write back. 

When I look at the link provided by you to the original repo I see following

```
def _neg_elbo(self, X, M, anneal = 1., dropout_prob = 0., additional = None):
        z_q, mu_q, cov_q   = self._q_z_x(X, mask = M, dropout_prob = dropout_prob, anneal = anneal)

        # KS : z_q belongs to t-1
        mu_trans, cov_trans= self._transition(z_q)
        mu_prior           = T.concatenate([T.zeros_like(mu_trans[:,[0],:]), mu_trans[:,:-1,:]], axis=1)
        cov_prior          = T.concatenate([T.ones_like(mu_trans[:,[0],:]),cov_trans[:,:-1,:]],axis=1)
        KL                 = self._temporalKL(mu_q, cov_q, mu_prior, cov_prior, mask = M)
       # KS: z_q belongs to t-1
        hid_out            = self._emission(z_q)
```

Look at the comment (marked as #KS); here `z_q` is obtained from previous time step t-1 and now it is "same" `z_q` being fed into both `transition` and `emission`. (I am assuming emission calls combiner)

Regards
Kapil

**Comment by yjlolo** [comment]
I believe the 'combiner' in the original repo is defined [here](https://github.com/clinicalml/dmm/blob/3a2e8cec5e58c5a141a6da6e685378e269e69bb8/model_th/dmm.py#L233);
and `_emission` defines `p(x_t | z_t)` which is [this function](https://github.com/yjlolo/pytorch-deep-markov-model/blob/3e606a3a4e2cf3474038b8fa539c6d8525d44abe/model/model.py#L115) in my implementation.

So in the original repo, `_transition` indeed takes the output from `_q_z_x` that composes LSTM and the combiner.

**Comment by ksachdeva** [comment]
Thanks @yjlolo 

Convinced now. Much appreciated.
